///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.Property
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ApplicantAddressFilter recording.
    /// </summary>
    [TestModule("4f6f888e-7578-44ff-9ba3-8b0291400faf", ModuleType.Recording, 1)]
    public partial class ApplicantAddressFilter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static ApplicantAddressFilter instance = new ApplicantAddressFilter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ApplicantAddressFilter()
        {
            Applicant_Address = "HUDSON STREET";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ApplicantAddressFilter Instance
        {
            get { return instance; }
        }

#region Variables

        string _Applicant_Address;

        /// <summary>
        /// Gets or sets the value of variable Applicant_Address.
        /// </summary>
        [TestVariable("e6f8cca1-a001-4ba9-a1e0-786656e92683")]
        public string Applicant_Address
        {
            get { return _Applicant_Address; }
            set { _Applicant_Address = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.Click_Filters' at Center.", repo.ApplicationUnderTest.Property.Click_FiltersInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Property.Click_Filters.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.Click_AddFilter' at Center.", repo.ApplicationUnderTest.Property.Click_AddFilterInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Property.Click_AddFilter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.Filter_RecordID' at Center.", repo.ApplicationUnderTest.Property.Filter_RecordIDInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Property.Filter_RecordID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Return}' with focus on 'ApplicationUnderTest.Property.Filter_RecordID'.", repo.ApplicationUnderTest.Property.Filter_RecordIDInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Property.Filter_RecordID.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.Filter_Equal' at Center.", repo.ApplicationUnderTest.Property.Filter_EqualInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Property.Filter_Equal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}{Return}' with focus on 'ApplicationUnderTest.Property.Filter_Equal'.", repo.ApplicationUnderTest.Property.Filter_EqualInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Property.Filter_Equal.PressKeys("{Up}{Up}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Applicant_Address' with focus on 'ApplicationUnderTest.Property.RefNo_Value'.", repo.ApplicationUnderTest.Property.RefNo_ValueInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Property.RefNo_Value.PressKeys(Applicant_Address);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
