///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.Property
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterAssertNameAddress recording.
    /// </summary>
    [TestModule("ddc501e9-9be3-4a5d-8496-928ff297a7f1", ModuleType.Recording, 1)]
    public partial class EnterAssertNameAddress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static EnterAssertNameAddress instance = new EnterAssertNameAddress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterAssertNameAddress()
        {
            Asset_Address = "103 AGRESS RD";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterAssertNameAddress Instance
        {
            get { return instance; }
        }

#region Variables

        string _Asset_Address;

        /// <summary>
        /// Gets or sets the value of variable Asset_Address.
        /// </summary>
        [TestVariable("ac54f1a4-e434-45ef-a460-2e3721f5d420")]
        public string Asset_Address
        {
            get { return _Asset_Address; }
            set { _Asset_Address = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.PropertyAddress_dropdown' at Center.", repo.ApplicationUnderTest.Property.PropertyAddress_dropdownInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Property.PropertyAddress_dropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Property.AssetName' at Center.", repo.ApplicationUnderTest.Property.AssetNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Property.AssetName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Asset_Address' with focus on 'ApplicationUnderTest.Property.Search_Asset'.", repo.ApplicationUnderTest.Property.Search_AssetInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Property.Search_Asset.PressKeys(Asset_Address);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'ApplicationUnderTest.Property.Search_Asset'.", repo.ApplicationUnderTest.Property.Search_AssetInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Property.Search_Asset.PressKeys("{Down}{Return}");
            Delay.Milliseconds(0);
            
            // Verifying Selected Asset address was displayed
            Report.Log(ReportLevel.Info, "Validation", "Verifying Selected Asset address was displayed\r\nValidating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.Property.Asset_Address'.", repo.ApplicationUnderTest.Property.Asset_AddressInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Property.Asset_AddressInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$Asset_Address) on item 'ApplicationUnderTest.Property.Asset_Address'.", repo.ApplicationUnderTest.Property.Asset_AddressInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Property.Asset_AddressInfo, "InnerText", Asset_Address);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
