///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CacheTheLotAndBlock recording.
    /// </summary>
    [TestModule("6f26f842-85b8-4165-af1b-71a4d2ddebc1", ModuleType.Recording, 1)]
    public partial class CacheTheLotAndBlock : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static CacheTheLotAndBlock instance = new CacheTheLotAndBlock();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CacheTheLotAndBlock()
        {
            CachedBlock = "";
            CachedLot = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CacheTheLotAndBlock Instance
        {
            get { return instance; }
        }

#region Variables

        string _CachedBlock;

        /// <summary>
        /// Gets or sets the value of variable CachedBlock.
        /// </summary>
        [TestVariable("8adc44b6-5a1a-45b4-b30c-66801b2bc282")]
        public string CachedBlock
        {
            get { return _CachedBlock; }
            set { _CachedBlock = value; }
        }

        string _CachedLot;

        /// <summary>
        /// Gets or sets the value of variable CachedLot.
        /// </summary>
        [TestVariable("77c5c77d-4442-46f0-ae31-5507e6b945fe")]
        public string CachedLot
        {
            get { return _CachedLot; }
            set { _CachedLot = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'ApplicationUnderTest.DataViewerGrid.SpanBlockOnDataViewer' and assigning its value to variable 'CachedBlock'.", repo.ApplicationUnderTest.DataViewerGrid.SpanBlockOnDataViewerInfo, new RecordItemIndex(0));
            CachedBlock = repo.ApplicationUnderTest.DataViewerGrid.SpanBlockOnDataViewer.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", CachedBlock, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'ApplicationUnderTest.DataViewerGrid.SpanLotOnDataViewer' and assigning its value to variable 'CachedLot'.", repo.ApplicationUnderTest.DataViewerGrid.SpanLotOnDataViewerInfo, new RecordItemIndex(2));
            CachedLot = repo.ApplicationUnderTest.DataViewerGrid.SpanLotOnDataViewer.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", CachedLot, new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
