///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeselectFewAndAddFewNewFields recording.
    /// </summary>
    [TestModule("1f5253c4-1623-45ec-95df-9ef2f4817796", ModuleType.Recording, 1)]
    public partial class DeselectFewAndAddFewNewFields : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static DeselectFewAndAddFewNewFields instance = new DeselectFewAndAddFewNewFields();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeselectFewAndAddFewNewFields()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeselectFewAndAddFewNewFields Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomePage.BtnFields' at Center.", repo.ApplicationUnderTest.HomePage.BtnFieldsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HomePage.BtnFields.Click();
            Delay.Milliseconds(0);
            
            // Deselecting Field Ref No.
            Report.Log(ReportLevel.Info, "Mouse", "Deselecting Field Ref No.\r\nMouse Left Click item 'ApplicationUnderTest.DataViewerGrid.SpanRefNum' at Center.", repo.ApplicationUnderTest.DataViewerGrid.SpanRefNumInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DataViewerGrid.SpanRefNum.Click();
            Delay.Milliseconds(0);
            
            // Deselecting Field Applicant Address
            Report.Log(ReportLevel.Info, "Mouse", "Deselecting Field Applicant Address\r\nMouse Left Click item 'ApplicationUnderTest.DataViewerGrid.ListItemApplicantAddress' at Center.", repo.ApplicationUnderTest.DataViewerGrid.ListItemApplicantAddressInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.DataViewerGrid.ListItemApplicantAddress.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DataViewerGrid.ListItemPetName' at Center.", repo.ApplicationUnderTest.DataViewerGrid.ListItemPetNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.DataViewerGrid.ListItemPetName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DataViewerGrid.ListItemBreedName' at Center.", repo.ApplicationUnderTest.DataViewerGrid.ListItemBreedNameInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.DataViewerGrid.ListItemBreedName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuppliClickObject' at Center.", repo.SuppliClickObjectInfo, new RecordItemIndex(5));
            repo.SuppliClickObject.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
