///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterEmailInTheRecord recording.
    /// </summary>
    [TestModule("6540530c-892c-4b2d-95a1-2b4d12cf746e", ModuleType.Recording, 1)]
    public partial class EnterEmailInTheRecord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static EnterEmailInTheRecord instance = new EnterEmailInTheRecord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterEmailInTheRecord()
        {
            EmailToTest = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterEmailInTheRecord Instance
        {
            get { return instance; }
        }

#region Variables

        string _EmailToTest;

        /// <summary>
        /// Gets or sets the value of variable EmailToTest.
        /// </summary>
        [TestVariable("e910c1f1-005a-41e7-b0a2-6a20c36f541e")]
        public string EmailToTest
        {
            get { return _EmailToTest; }
            set { _EmailToTest = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.CreateNewScreen.TxtEmail'", repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtEmail' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.CreateNewScreen.TxtEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$EmailToTest' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtEmail'.", repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.CreateNewScreen.TxtEmail.PressKeys(EmailToTest);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.BtnSave' at Center.", repo.ApplicationUnderTest.CreateNewScreen.BtnSaveInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CreateNewScreen.BtnSave.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
