///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillFOrmDetailsWithEdit recording.
    /// </summary>
    [TestModule("daaa2341-a24a-4e72-b621-b0f530c1fcb8", ModuleType.Recording, 1)]
    public partial class FillFOrmDetailsWithEdit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static FillFOrmDetailsWithEdit instance = new FillFOrmDetailsWithEdit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillFOrmDetailsWithEdit()
        {
            FirstName = "";
            SecondName = "yourtext";
            PhoneNumber = "";
            Email1 = "yourtext";
            Address2 = "yourtext";
            DogName = "yourtext";
            BreedInput = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillFOrmDetailsWithEdit Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("2821e5c5-6261-4dd2-b3df-26512af04574")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _SecondName;

        /// <summary>
        /// Gets or sets the value of variable SecondName.
        /// </summary>
        [TestVariable("8037a600-c879-4b03-abfb-e650529cb202")]
        public string SecondName
        {
            get { return _SecondName; }
            set { _SecondName = value; }
        }

        string _PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable PhoneNumber.
        /// </summary>
        [TestVariable("6d17ff1b-5d07-4e87-b4b5-0873fb30b092")]
        public string PhoneNumber
        {
            get { return _PhoneNumber; }
            set { _PhoneNumber = value; }
        }

        string _Email1;

        /// <summary>
        /// Gets or sets the value of variable Email1.
        /// </summary>
        [TestVariable("84633124-40ce-4869-a287-8ec532d4cb8f")]
        public string Email1
        {
            get { return _Email1; }
            set { _Email1 = value; }
        }

        string _Address2;

        /// <summary>
        /// Gets or sets the value of variable Address2.
        /// </summary>
        [TestVariable("f13afd65-7bfd-4ba0-8160-ff259bf1a82f")]
        public string Address2
        {
            get { return _Address2; }
            set { _Address2 = value; }
        }

        string _DogName;

        /// <summary>
        /// Gets or sets the value of variable DogName.
        /// </summary>
        [TestVariable("fa69b9ae-6377-4687-87a0-6853e0d36cd1")]
        public string DogName
        {
            get { return _DogName; }
            set { _DogName = value; }
        }

        string _BreedInput;

        /// <summary>
        /// Gets or sets the value of variable BreedInput.
        /// </summary>
        [TestVariable("1c0f6f1f-3374-460b-b7df-163b7df88f84")]
        public string BreedInput
        {
            get { return _BreedInput; }
            set { _BreedInput = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtFirstName' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtFirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.CreateNewScreen.TxtFirstName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtFirstName'.", repo.ApplicationUnderTest.CreateNewScreen.TxtFirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.CreateNewScreen.TxtFirstName.PressKeys(FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtSecondName' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtSecondNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.CreateNewScreen.TxtSecondName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SecondName' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtSecondName'.", repo.ApplicationUnderTest.CreateNewScreen.TxtSecondNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.CreateNewScreen.TxtSecondName.PressKeys(SecondName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNum' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNumInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNum.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PhoneNumber' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNum'.", repo.ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNumInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.CreateNewScreen.TxtOwnerPhoneNum.PressKeys(PhoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtEmail' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.CreateNewScreen.TxtEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Email1' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtEmail'.", repo.ApplicationUnderTest.CreateNewScreen.TxtEmailInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.CreateNewScreen.TxtEmail.PressKeys(Email1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtAddress2' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtAddress2Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.CreateNewScreen.TxtAddress2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Address2' with focus on 'ApplicationUnderTest.CreateNewScreen.TxtAddress2'.", repo.ApplicationUnderTest.CreateNewScreen.TxtAddress2Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.CreateNewScreen.TxtAddress2.PressKeys(Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.Txt_DogName' at Center.", repo.ApplicationUnderTest.CreateNewScreen.Txt_DogNameInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.CreateNewScreen.Txt_DogName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DogName' with focus on 'ApplicationUnderTest.CreateNewScreen.Txt_DogName'.", repo.ApplicationUnderTest.CreateNewScreen.Txt_DogNameInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.CreateNewScreen.Txt_DogName.PressKeys(DogName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.TxtBreedInput' at Center.", repo.ApplicationUnderTest.CreateNewScreen.TxtBreedInputInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.CreateNewScreen.TxtBreedInput.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ApplicationUnderTest.CreateNewScreen.TxtBreedInput'.", repo.ApplicationUnderTest.CreateNewScreen.TxtBreedInputInfo, new RecordItemIndex(13));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.CreateNewScreen.TxtBreedInput);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Key_sequence_TxtBreedInput(repo.ApplicationUnderTest.CreateNewScreen.TxtBreedInputInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}'.", new RecordItemIndex(15));
            Keyboard.Press("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.BtnSaveAndClose' at Center.", repo.ApplicationUnderTest.CreateNewScreen.BtnSaveAndCloseInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.CreateNewScreen.BtnSaveAndClose.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            // Verifying that edit form screen does not exist after Saving and Closing it
            //Report.Log(ReportLevel.Info, "Validation", "Verifying that edit form screen does not exist after Saving and Closing it\r\nValidating NotExists on item 'ApplicationUnderTest.HomePage.TabDisplayingAddress'.", repo.ApplicationUnderTest.HomePage.TabDisplayingAddressInfo, new RecordItemIndex(18));
            //Validate.NotExists(repo.ApplicationUnderTest.HomePage.TabDisplayingAddressInfo);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
