///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchAndDeleteARecord recording.
    /// </summary>
    [TestModule("69c3af90-d8fa-44c4-b668-4254b3de965e", ModuleType.Recording, 1)]
    public partial class LaunchAndDeleteARecord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static LaunchAndDeleteARecord instance = new LaunchAndDeleteARecord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchAndDeleteARecord()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchAndDeleteARecord Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomePage.IconViewForm' at Center.", repo.ApplicationUnderTest.HomePage.IconViewFormInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HomePage.IconViewForm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ViewFormPage.BtnDelete' at Center.", repo.ApplicationUnderTest.ViewFormPage.BtnDeleteInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ViewFormPage.BtnDelete.Click();
            Delay.Milliseconds(0);
            
            // Verifying If Delete Confirmation Dialog Box Displays
            Report.Log(ReportLevel.Info, "Validation", "Verifying If Delete Confirmation Dialog Box Displays\r\nValidating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.ViewFormPage.DialogConfirmDelete'.", repo.ApplicationUnderTest.ViewFormPage.DialogConfirmDeleteInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ViewFormPage.DialogConfirmDeleteInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ViewFormPage.BtnCancel' at Center.", repo.ApplicationUnderTest.ViewFormPage.BtnCancelInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.ViewFormPage.BtnCancel.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ViewFormPage.BtnDelete' at Center.", repo.ApplicationUnderTest.ViewFormPage.BtnDeleteInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ViewFormPage.BtnDelete.Click();
            Delay.Milliseconds(0);
            
            // Verifying If Delete Confirmation Dialog Box Displays
            Report.Log(ReportLevel.Info, "Validation", "Verifying If Delete Confirmation Dialog Box Displays\r\nValidating Exists on item 'ApplicationUnderTest.ViewFormPage.DialogConfirmDelete'.", repo.ApplicationUnderTest.ViewFormPage.DialogConfirmDeleteInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ApplicationUnderTest.ViewFormPage.DialogConfirmDeleteInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ViewFormPage.BtnOK' at Center.", repo.ApplicationUnderTest.ViewFormPage.BtnOKInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.ViewFormPage.BtnOK.Click();
            Delay.Milliseconds(0);
            
            // Verifying that Delete COnfirmation Acknowledgement Displays
            Report.Log(ReportLevel.Info, "Validation", "Verifying that Delete COnfirmation Acknowledgement Displays\r\nValidating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.ViewFormPage.ConfirmDeleteMessage'.", repo.ApplicationUnderTest.ViewFormPage.ConfirmDeleteMessageInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ViewFormPage.ConfirmDeleteMessageInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ViewFormPage.BtnOkOnConfirmDialog' at Center.", repo.ApplicationUnderTest.ViewFormPage.BtnOkOnConfirmDialogInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ViewFormPage.BtnOkOnConfirmDialog.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
