///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectModuleAndViewFormClose recording.
    /// </summary>
    [TestModule("e2cfd098-9aea-44d4-a2a0-00e7a474e0c7", ModuleType.Recording, 1)]
    public partial class SelectModuleAndViewFormClose : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static SelectModuleAndViewFormClose instance = new SelectModuleAndViewFormClose();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectModuleAndViewFormClose()
        {
            ModuleName = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectModuleAndViewFormClose Instance
        {
            get { return instance; }
        }

#region Variables

        string _ModuleName;

        /// <summary>
        /// Gets or sets the value of variable ModuleName.
        /// </summary>
        [TestVariable("b27cafbb-9060-41be-b4a9-4c429f42498e")]
        public string ModuleName
        {
            get { return _ModuleName; }
            set { _ModuleName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomePage.IconViewForm' at Center.", repo.ApplicationUnderTest.HomePage.IconViewFormInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HomePage.IconViewForm.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CreateNewScreen.BtnNew' at Center.", repo.ApplicationUnderTest.CreateNewScreen.BtnNewInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.CreateNewScreen.BtnNew.Click();
            Delay.Milliseconds(0);
            
            // Validating If Save Button Displays After Form Opens Up as New
            Report.Log(ReportLevel.Info, "Validation", "Validating If Save Button Displays After Form Opens Up as New\r\nValidating Exists on item 'ApplicationUnderTest.CreateNewScreen.BtnSave'.", repo.ApplicationUnderTest.CreateNewScreen.BtnSaveInfo, new RecordItemIndex(2));
            Validate.Exists(repo.ApplicationUnderTest.CreateNewScreen.BtnSaveInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to exist. Associated repository item: 'ApplicationUnderTest.CreateNewScreen.BtnClose'", repo.ApplicationUnderTest.CreateNewScreen.BtnCloseInfo, new ActionTimeout(15000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.CreateNewScreen.BtnCloseInfo.WaitForExists(15000);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'ApplicationUnderTest.CreateNewScreen.BtnClose'.", repo.ApplicationUnderTest.CreateNewScreen.BtnCloseInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CreateNewScreen.BtnClose.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.CreateNewScreen.BtnClose'.", repo.ApplicationUnderTest.CreateNewScreen.BtnCloseInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.CreateNewScreen.BtnClose.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
