///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SortAscendingOnRecordIDAndCacheIt recording.
    /// </summary>
    [TestModule("8208e07c-522a-4ce2-b7f5-42408c71c2f0", ModuleType.Recording, 1)]
    public partial class SortAscendingOnRecordIDAndCacheIt : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static SortAscendingOnRecordIDAndCacheIt instance = new SortAscendingOnRecordIDAndCacheIt();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SortAscendingOnRecordIDAndCacheIt()
        {
            RecordIDFetched = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SortAscendingOnRecordIDAndCacheIt Instance
        {
            get { return instance; }
        }

#region Variables

        string _RecordIDFetched;

        /// <summary>
        /// Gets or sets the value of variable RecordIDFetched.
        /// </summary>
        [TestVariable("dfe7e7d7-6789-43d5-a34b-e33806e1a734")]
        public string RecordIDFetched
        {
            get { return _RecordIDFetched; }
            set { _RecordIDFetched = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuppliClickObject' at Center.", repo.SuppliClickObjectInfo, new RecordItemIndex(0));
            repo.SuppliClickObject.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.LogsScreen.TdRecordIDNew' and assigning its value to variable 'RecordIDFetched'.", repo.ApplicationUnderTest.LogsScreen.TdRecordIDNewInfo, new RecordItemIndex(1));
            RecordIDFetched = repo.ApplicationUnderTest.LogsScreen.TdRecordIDNew.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", RecordIDFetched, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
