///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using System.Globalization;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.DataViewer
{
    public partial class VerifyEditedOnMatchesTheSysDate
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Get_value_ValueEditedOnDate(RepoItemInfo tdtagInfo)
        {
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'tdtagInfo' and assigning its value to variable 'EditedOnGenerated'.", tdtagInfo);
            EditedOnGenerated = tdtagInfo.FindAdapter<TdTag>().Element.GetAttributeValueText("InnerText");
           
            // Parse the original date string to a DateTime object

             System.DateTime originalDate = System.DateTime.ParseExact(EditedOnGenerated, "MM/dd/yyyy hh:mm:ss tt", CultureInfo.InvariantCulture);

             System.DateTime trimmedDate = new System.DateTime(originalDate.Year, originalDate.Month, originalDate.Day, originalDate.Hour, originalDate.Minute, 0, originalDate.Kind);
			 string trimmedDateStr = trimmedDate.ToString("M/d/yy hh", CultureInfo.InvariantCulture);

             System.DateTime currentDate = System.DateTime.Now;
			string formattedSysDate = currentDate.ToString("M/d/yy hh", CultureInfo.InvariantCulture);            
			
			if (trimmedDateStr.Contains (formattedSysDate))
	
	            {
	
	                Report.Log(ReportLevel.Info, "Record Editing date and time matches the current system date and time", trimmedDateStr);
	
	            }
			else
	
	            {
	
	                Report.Log(ReportLevel.Info, "Record Editing date and time does not match the current system date and time", trimmedDateStr);
	
	                Report.Log(ReportLevel.Info, "Your current system date and time is", formattedSysDate);
	
	                Report.Failure("Test Failed", "Date Mismatch");
	
	            }
        }

    }
}
