///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.Homescreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateFifthView recording.
    /// </summary>
    [TestModule("221c14cc-4424-493e-aa7a-14f09eb6a641", ModuleType.Recording, 1)]
    public partial class CreateFifthView : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static CreateFifthView instance = new CreateFifthView();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateFifthView()
        {
            ViewName5 = "";
            BreedValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateFifthView Instance
        {
            get { return instance; }
        }

#region Variables

        string _ViewName5;

        /// <summary>
        /// Gets or sets the value of variable ViewName5.
        /// </summary>
        [TestVariable("28fe14ed-bee6-4d87-8c19-62c852cebf97")]
        public string ViewName5
        {
            get { return _ViewName5; }
            set { _ViewName5 = value; }
        }

        string _BreedValue;

        /// <summary>
        /// Gets or sets the value of variable BreedValue.
        /// </summary>
        [TestVariable("3e370ba5-2e8c-4949-b2fc-b92d3fb39d60")]
        public string BreedValue
        {
            get { return _BreedValue; }
            set { _BreedValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Txt_ViewName_All'", repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo, new ActionTimeout(10000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Txt_ViewName_All'", repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo.WaitForAttributeEqual(10000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new ActionTimeout(10000), new RecordItemIndex(2));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForAttributeEqual(10000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Filter' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Filter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new ActionTimeout(10000), new RecordItemIndex(8));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForAttributeEqual(5000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter' at Center.", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "The BreedName is selected from the Dropdown", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new ActionTimeout(5000), new RecordItemIndex(13));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 12} ' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.PressKeys("{Down 12} ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(16));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.PressKeys("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(18));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "User", "The Relational Operator here has contains value", new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new ActionTimeout(5000), new RecordItemIndex(20));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$BreedValue' with focus on 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'.", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status.PressKeys(BreedValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(22));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}' with focus on 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'.", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status.PressKeys("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(24));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new ActionTimeout(5000), new RecordItemIndex(25));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Filter' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Filter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "The Records are filtered based on the Column BreedName contains value Mix", new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(28));
            Delay.Duration(500, false);
            
            HelperClass.SaveView(ViewName5);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Saved Fifth View successfully post filteration of records that contains Breed value Mix", new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(31));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.DogLicensePage.Btn_Closeview'.", repo.ApplicationUnderTest.DogLicensePage.Btn_CloseviewInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.DogLicensePage.Btn_CloseviewInfo, "Visible", "True", null, new Validate.Options(){GracePeriod=5000});
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Closeview' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_CloseviewInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Closeview.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.HomePage.Table_RecentRecords'", repo.ApplicationUnderTest.HomePage.Table_RecentRecordsInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.HomePage.Table_RecentRecordsInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
