///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GovPilot.GovPilotRecordings.SmokeRecordings.Homescreen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateSecondView recording.
    /// </summary>
    [TestModule("9bf55535-394a-420e-a0ae-1897d1c99ad8", ModuleType.Recording, 1)]
    public partial class CreateSecondView : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::GovPilot.GovPilotRepository repository.
        /// </summary>
        public static global::GovPilot.GovPilotRepository repo = global::GovPilot.GovPilotRepository.Instance;

        static CreateSecondView instance = new CreateSecondView();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateSecondView()
        {
            ViewName2 = "";
            StatusValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateSecondView Instance
        {
            get { return instance; }
        }

#region Variables

        string _ViewName2;

        /// <summary>
        /// Gets or sets the value of variable ViewName2.
        /// </summary>
        [TestVariable("10b436e5-5ad7-4f59-bbc8-24ef3ae04990")]
        public string ViewName2
        {
            get { return _ViewName2; }
            set { _ViewName2 = value; }
        }

        string _StatusValue;

        /// <summary>
        /// Gets or sets the value of variable StatusValue.
        /// </summary>
        [TestVariable("df187afc-fff1-4d35-89d4-07239aa32b17")]
        public string StatusValue
        {
            get { return _StatusValue; }
            set { _StatusValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Txt_ViewName_All'", repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo, new ActionTimeout(10000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Txt_ViewName_All'", repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DogLicensePage.Txt_ViewName_AllInfo.WaitForAttributeEqual(10000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForAttributeEqual(10000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Filter' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Filter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new ActionTimeout(5000), new RecordItemIndex(7));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter'", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo.WaitForAttributeEqual(10000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter' at Center.", repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilterInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.DogLicensePage.BtnIcon_AddFilter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "The Status Column Option is Selected from the Dropdown", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new ActionTimeout(5000), new RecordItemIndex(12));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down 6} ' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.PressKeys("{Down 6} ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(15));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_FavouriteInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_Favourite.PressKeys("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(17));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp'", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOpInfo, new ActionTimeout(5000), new RecordItemIndex(18));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOpInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOpInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down} ' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOpInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp.PressKeys("{Down} ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(21));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}' with focus on 'ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp'.", repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOpInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Drpdown_RelationalOp.PressKeys("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(23));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "User", "The Relational Operator that does not contain New in Status Column are added to the Filter", new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new ActionTimeout(5000), new RecordItemIndex(25));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$StatusValue' with focus on 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'.", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status.PressKeys(StatusValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 200ms.", new RecordItemIndex(27));
            Delay.Duration(200, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Enter}' with focus on 'ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status'.", repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_StatusInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.DogLicensePage.TxtBox_FilterValue_Status.PressKeys("{Enter}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "User", "The Records are filtered based on the  Status column that should not contain the value New", new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.DogLicensePage.Btn_Filter'", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new ActionTimeout(5000), new RecordItemIndex(31));
            repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DogLicensePage.Btn_Filter' at Center.", repo.ApplicationUnderTest.DogLicensePage.Btn_FilterInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.DogLicensePage.Btn_Filter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(33));
            Delay.Duration(500, false);
            
            HelperClass.SaveView(ViewName2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Saved Second View successfully post filteration of only Non-New Status Records", new RecordItemIndex(35));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(36));
            Delay.Duration(300, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
